_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.9.13
        t:
            "1":
                - 1
                - 11
                - 49
            "2":
                - 1
                - 11
                - 49
            "3":
                - 2
                - 55
            "4": 3.9.13
            "5": 0.20.1
            "6": 4.52.4
            "8":
                - 3
            "12": 0.20.1
            "13": windows-amd64
